name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: FlotMaximum/FlotMaximum.sln
      Test_Project_Path: FlotMaximum/Tests/Tests.csproj
      GUROBI_WLS_ACCESS_ID: ${{ secrets.GUROBI_WLS_ACCESS_ID }}
      GUROBI_WLS_SECRET_KEY: ${{ secrets.GUROBI_WLS_SECRET_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install Gurobi 12.0.1
      run: |
        Invoke-WebRequest -Uri https://packages.gurobi.com/12.0/Gurobi-12.0.1-win64.msi -OutFile gurobi.msi
        Start-Process msiexec.exe -ArgumentList '/i', 'gurobi.msi', '/quiet', '/norestart' -NoNewWindow -Wait
        echo "GUROBI_HOME=C:\gurobi\gurobi1201\win64" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "Path=$env:GUROBI_HOME\bin;$env:Path" | Out-File -FilePath $env:GITHUB_ENV -Append
        
        # Créer le fichier de licence à partir du secret
        echo "${{ secrets.GUROBI_LICENSE }}" | Out-File -FilePath "C:\gurobi\gurobi1201\win64\gurobi.lic"

    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
